### ISSUE TITLE
Support windows authentication

### ISSUE THREAD

**Issue by juancentro** [hs3180/dplyr.sqlserver#4]
Hi, the package doesn't support windows integrated authentication now, right? Do you know if the underlying DBI package supports it?

**Comment by hs3180** [comment]
I am sorry that I have left my ex-job and don't use mssql server any more. this project was established on the [Microsoft JDBC Driver for SQL Server](https://msdn.microsoft.com/en-us/sqlserver/aa937724.aspx). You may solve this problem by yourself, and PR is welcome. :)

**Comment by Jim89** [comment]
That's alright - I've left too so not a problem now!

On Mon, 21 Sep 2015 08:58 Shan Huang <notifications@github.com> wrote:

> I am sorry that I have left my ex-job and don't use mssql server any more.
> this project was established on the Microsoft JDBC Driver for SQL Server
> <https://msdn.microsoft.com/en-us/sqlserver/aa937724.aspx>. You may solve
> this problem by yourself, and PR is welcome. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hs3180/dplyr.sqlserver/issues/4#issuecomment-141902616>
> .
>
-- 

Jim Leach

07711 910 607
